### ISSUE TITLE
DyNeRF implementation

### ISSUE THREAD

**Issue by aaryapatel007** [sarafridov/K-Planes#10]
Hey @sarafridov, 
I am impressed with the results you've got with the K-Planes.
Within the paper, you compare your results with DyNeRF model. I'm curious to experiment with the DyNeRF model, so can you please provide your implementation of DyNeRF?

Thank you!

**Comment by Giodiro** [comment]
Hi @aaryapatel007 
We did not re-implement the DyNeRF model for our paper, we reported results from the original work.
