### ISSUE TITLE
Blender evaluation split

### ISSUE THREAD

**Issue by hturki** [sarafridov/K-Planes#11]
Thanks for the great work! When running this code on the blender dataset I get metrics that line up with the paper. However, looking at https://github.com/sarafridov/K-Planes/blob/main/plenoxels/datasets/synthetic_nerf_dataset.py#L36, I think that we're both training and testing against the "test" split vs training on the train split and then evaluating on the held out test set. Is this intentional or am I misunderstanding what's going on?

**Comment by sarafridov** [comment]
Good catch! This looks like a bug for that dataset loader; fixing it now (and will update the results tables). Thanks for bringing it to my attention.

**Comment by sarafridov** [comment]
All fixed now! (updated arxiv will come out tomorrow, and CVPR cameraready is also fixed). Thanks again for pointing this out.
