### ISSUE TITLE
About the memory needed for training cut_roasted_beef video with dynerf_hybird config file

### ISSUE THREAD

**Issue by wangyuyy** [sarafridov/K-Planes#16]
Hi sarafridov,
    Thanks for sharing the code of your great project.
    I wonder how much memory is needef for training cut_roasted_beef video with dynerf_hybird config file. The memory of my machine is 256G, the processes failed all the time for lack of memory.

**Comment by wangyuyy** [comment]
Thanks for your help. I tried as you said, but the process stopped at 'Loading test data' with no response or reported error. 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/106719785/230045557-74f4df58-0864-448b-a7bc-7e16b697fb68.png">

**Comment by Giodiro** [comment]
Yeah that can happen sometimes, it's a concurrency bug in multi-threaded loading.. It's annoying but if you ctrl+c and try again it should work. Let me know if it's still not loading

**Comment by wangyuyy** [comment]
I tried to run main.py again for about 8 times, it all failed with the same problem. Got no idea what to do. Appreciate it a lot for your generous help.

**Comment by sarafridov** [comment]
I'm not sure if this will fix the issue or not, but if it's related to multithreading you could try reducing the number of threads here https://github.com/sarafridov/K-Planes/blob/main/plenoxels/datasets/data_loading.py#L144

**Comment by wangyuyy** [comment]
I tried so, but it's still not working. Is there other way to solve the problem?

**Comment by sarafridov** [comment]
Do you have this issue with other datasets (e.g. D-NeRF, or regular NeRF) or do those load properly? Also, are you getting this issue in the initial preprocessing run at downsample=4, or after that when you try to actually train at downsample=2?

**Comment by wangyuyy** [comment]
That's really weird, after about 25 times running, it finally works. The issue occurred only in reading test data. While the iterator was successfully created by Pool.imap and tqdm info was outputed, it makes no sense that the process stopped at 'out=next(iterator)'.
I'm sure it's not the problem of slow speed of reading data, since the longest time I waited was a whole night.
