### ISSUE TITLE
training on black background videos

### ISSUE THREAD

**Issue by y-zheng18** [sarafridov/K-Planes#17]
Hi, thanks for your great work! I'm trying to play with the repo, and I found that when I trained the model with RGBA images as follows, it worked fine.
![r_000](https://user-images.githubusercontent.com/51361119/230451560-ba46fd67-b608-426a-8c26-452385a0401c.png)

But when I replace the data with RGB files as follows, the novel view synthesis results are broken.
![r_000](https://user-images.githubusercontent.com/51361119/230451619-269120a5-2d30-4148-85da-cf02ff25f36b.png)
I tried to set bg_ground color as 0 [here]( https://github.com/sarafridov/K-Planes/blob/main/plenoxels/datasets/video_datasets.py#L292), but then it turned out that the network can't convergence during training (everything is black). What might be the solution?

**Comment by sarafridov** [comment]
If I understand correctly, you are trying to train with input images that are RGB with black background, but no explicit alpha channel. Is it possible that the dataloader mistakenly thinks that your alpha channel is all zeros? Then it would fill in the background with 0 and train on images that are all black. That doesn't seem super likely but it's worth checking and easy to fix by just adding an alpha channel that's all ones (and keeping bg_color=0). I'm not sure what else would cause this.
