### ISSUE TITLE
scene_box on DyNeRF dataset

### ISSUE THREAD

**Issue by ghy0324** [sarafridov/K-Planes#20]
Hi! Thanks for your excellent work!
I am wondering that do you use unified `scene_box` on all scenes of DyNeRF dataset?
https://github.com/sarafridov/K-Planes/blob/08533b5238d18bf71f4f2402ec6234cde530b2b8/plenoxels/configs/final/DyNeRF/dynerf_hybrid.py#L17
If not, could you provide the parameter of other scenes.

**Comment by Giodiro** [comment]
Hi @ghy0324 , we use the same bbox on all dynerf scenes!

**Comment by ghy0324** [comment]
Thanks for your prompt reply!
