### ISSUE TITLE
Please provide a set of parameters to reproduce the results on the lego dataset

### ISSUE THREAD

**Issue by wzy-99** [sarafridov/K-Planes#25]
Hi, I trained the lego dataset using the default parameters of kplanes, but the PSNR is very low.

Could the authors please provide the best parameters for reproducing the results of the paper on such datasets

**Comment by sarafridov** [comment]
Just checking that you used the appropriate config file (either of https://github.com/sarafridov/K-Planes/tree/main/plenoxels/configs/final/NeRF)? These are exactly the parameters we used.

**Comment by wzy-99** [comment]
Thank you very much.
I have reproduced the results of the paper
