### ISSUE TITLE
Bad performance on other dataset.

### ISSUE THREAD

**Issue by qhdqhd** [sarafridov/K-Planes#31]
Thanks for your great work!
I test your method on the blender dataset (lego), and I get good results.
However, when I test it on "fox" data from instant-ngp, the result is very bad.
![$2 LH{IW`7LN4LCFGRPYI2K](https://github.com/sarafridov/K-Planes/assets/42370719/278aeaa7-3d63-4cac-9fd3-445b502055df)
In addition, the results are also bad on the nerfstudio dataset:    "poster"("https://drive.google.com/file/d/1dmjWGXlJnUxwosN6MVooCDQe970PkD-1/view?usp=sharing"),

I wonder why? Thank you!

**Comment by sarafridov** [comment]
I haven't tested on either of those datasets, but my guess would be to check two things (1) make sure that the camera poses are provided in the same format as the NeRF dataset, and (2) for unbounded scenes, make sure that you are using an unbounded config (ie with scene contraction enabled). There may also be some manual tuning of the scene center/offset to make sure that it's making use of the foreground/uncontracted part of the planes.

**Comment by qhdqhd** [comment]
Thank you!
I change near_plane from 2 to 0.01 and far_plane from 6 to 1000.
And It is successful!

**Comment by liuxin2322** [comment]
> Thank you! I change near_plane from 2 to 0.01 and far_plane from 6 to 1000. And It is successful!

I met same issue, where can i find and modify the parameter about near plane and far_plane ?
