### ISSUE TITLE
Performance on TanksandTemple dataset

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [sarafridov/K-Planes#33]
Dear author, thanks for open source your work!

I am currently using Kplanes on TanksandTemple datasets with both nerf explicit and hybrid hyper parameters. However, the scene reconstruction quality is not too good (very blurry background and cannot render the object of interest). I am wondering if you have experience with your method on TanksandTemple dataset? I appreciate it if you can provide an insight.

Thank you
![Screenshot 2023-08-22 at 1 03 20 pm](https://github.com/sarafridov/K-Planes/assets/33888801/4baefd2f-a347-49fc-be77-0502989ccf93)
![step30000-1](https://github.com/sarafridov/K-Planes/assets/33888801/dc82a5f2-3461-4914-80e4-d4bdee944eea)

**Comment by sarafridov** [comment]
I haven't tested with Tanks and Temples, but I can give some suggestions of things to check and hopefully one of them resolves the issue, but feel free to follow up if not.
1. Double check that you are using a config file intended for unbounded scenes (e.g. following the first chunk of parameters in the config files for the Phototourism scenes); in particular make sure that scene contraction is enabled with a scene_bbox from -2 to 2 in each dimension.
2. If that still produces subpar results, the next thing to check is to visualize the planes learned by the model. Ideally the foreground object is in the center of the planes (where the resolution is highest), and the scene itself mostly fills each plane but isn't too cramped against the edges. If you see that the scene is not well aligned with the planes, you can fix it by adjusting the global_scale and global_translation parameters in the config.

**Comment by RongKaiWeskerMA** [comment]
> I haven't tested with Tanks and Temples, but I can give some suggestions of things to check and hopefully one of them resolves the issue, but feel free to follow up if not.
> 
> 1. Double check that you are using a config file intended for unbounded scenes (e.g. following the first chunk of parameters in the config files for the Phototourism scenes); in particular make sure that scene contraction is enabled with a scene_bbox from -2 to 2 in each dimension.
> 2. If that still produces subpar results, the next thing to check is to visualize the planes learned by the model. Ideally the foreground object is in the center of the planes (where the resolution is highest), and the scene itself mostly fills each plane but isn't too cramped against the edges. If you see that the scene is not well aligned with the planes, you can fix it by adjusting the global_scale and global_translation parameters in the config.

Thanks for the prompt reply! I will see how it goes.
