### ISSUE TITLE
Replicating Fig 8 from the paper

### ISSUE THREAD

**Issue by azzarelli** [sarafridov/K-Planes#35]
Hi,

I am a bit stuck on how to visualise the results as was done in Figure 8 in the paper - i.e. visualising _xt_ (and yt, zt).  Is there a function which I may have missed?

If not:
I've currently modified `plenoxels.models.kplanes_field.interpolate_ms_features` function to evaluate a selected grid (e.g. grid (0, 2), which is one of the time-plane grid) rather than all the grids. The code then interpolates the different scales and renders the result, which I assumed was the xt plane. I'm not really sure this is correct, so I'm wondering if there are any better approaches?

**Comment by Giodiro** [comment]
Hi @azzarelli ,
What we're doing in the paper is just plotting the features themselves (so given a `LowrankModel`, take `model.field.grids[scale_index][plane_index]`) picking a single scale and plane and then averaging over all features to get a 2D tensor.

**Comment by azzarelli** [comment]
Hi @Giodiro,

I see, thank you!
